name: ni_trades
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    convex_bottom_bar: ^2.4.0
    animated_text_kit: ^2.2.0
    modal_bottom_sheet: ^2.0.0
    currency_text_input_formatter: ^2.0.1
    pin_code_fields: ^7.2.0
    shared_preferences: ^2.0.5
    awesome_dialog: ^2.0.0
    entry: ^0.0.2+2
    flutter_spinkit: ^5.0.0
    palette_generator: ^0.3.0
#    hexcolor: ^2.0.4
    badges: ^1.1.3
    flutter_svg: ^0.21.0-nullsafety.0
    grouped_list: ^3.7.1
    page_transition: ^2.0.1-nullsafety.0
    image_picker: ^0.7.3
    image_cropper: ^1.4.0
    percent_indicator: ^3.0.1
    screenshot: ^0.3.0
    path_provider: ^2.0.1
    form_field_validator: ^1.1.0
    flutter_paystack: ^1.0.5
    getwidget: ^2.0.1-nullsafety.4
    sk_onboarding_screen:
        git:
            url: 'https://github.com/zubisofts/SKOnboardingScreen.git'
            ref: master
    equatable: ^2.0.0
    bloc: ^7.0.0
    flutter_bloc: ^7.0.0
    get_it: ^7.2.0
    sentry_flutter: ^5.1.0
    http: ^0.13.0
    permission_handler: ^3.0.0
    meta: ^1.1.8
    intl: ^0.17.0
    uuid: 3.0.4
    shimmer: ^2.0.0
    cached_network_image: ^3.0.0
    bubble: ^1.1.9+1
    firebase_core: ^1.0.2
    firebase_auth: ^1.0.1
    firebase_storage: ^8.0.1
    cloud_firestore: ^1.0.3
    onesignal_flutter: ^3.0.0
dev_dependencies:
    flutter_test:
        sdk: flutter

dependency_overrides:
    platform: ^3.1.0
    
flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/
        - assets/files/
    fonts:
        -
            family: Proxima
            fonts:
                -
                    asset: assets/fonts/proxima_regular.otf
        -
            family: Poppins-Bold
            fonts:
                -
                    asset: assets/fonts/Poppins-Bold.ttf
        -
            family: Poppins-Medium
            fonts:
                -
                    asset: assets/fonts/Poppins-Medium.ttf
        -
            family: Poppins-Light
            fonts:
                -
                    asset: assets/fonts/Poppins-Light.otf
        -
            family: Poppins-ExtraLight
            fonts:
                -
                    asset: assets/fonts/Poppins-ExtraLight.otf
        -
            family: Poppins-Regular
            fonts:
                -
                    asset: assets/fonts/Poppins-Regular.otf
        -
            family: Poppins-SemiBold
            fonts:
                -
                    asset: assets/fonts/Poppins-SemiBold.otf
        -
            family: BR Firma Bold
            fonts:
                -
                    asset: assets/fonts/BR_Firma_Bold.otf
        -
            family: BR Firma Medium
            fonts:
                -
                    asset: assets/fonts/BR_Firma_Medium.otf
        -
            family: BR Firma Regular
            fonts:
                -
                    asset: assets/fonts/BR_Firma_Regular.otf
        -
            family: BR Firma Black
            fonts:
                -
                    asset: assets/fonts/BR_Firma_Black.otf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages